### ISSUE TITLE
Add dedicated page/sandbox for each HoistInput 

### ISSUE THREAD

**Issue by lbwexler** [xh/toolbox#248]
Should come up with a general shared component to host the control, and provide toggles to manipulate all of its props.

**Comment by lbwexler** [comment]
Am taking a look at this and setting it up.  Will reach out for design help when necessary.

**Comment by peterjcoffman** [comment]
At the moment I am blocked on this due to some issues in hoist-react. I've opened tickets for those and they might get fixed soon.

https://github.com/uber/react-view/issues/9
https://github.com/uber/react-view/issues/8

Here are my notes on what remains to be done:

Things that remain to be done:
        1. Move value display away from control
	2. Add title to knobs column
	3. Add defaults and placeholders as needed, especially on complicated props the user can’t be expected to figure out.
	4. Maybe split select into two tabs, one for queries and one for “normal” select?

Many of the props need another look:
Some prop

Some props seem broken or useless.
- autofocus seems to work on all examples, but in a confusing way.
- Inline seems to do nothing on any example.
- Fill seems to do nothing on any example.
- DateInput valueType is broken.
    - To break it:

      1.  Set valueType to localDate.
      2. Enter a date using the date picker.
      3. Set valueType to date.
      4. Enter a date using the date picker.
    - The dateInput will break. It will no longer work at all with valueType set to date. I can’t get it to work again without reloading the page.
- DateInput popoverPosition is currently set up as a text input. We really want it to be a select with the proper strings displayed, but this seems impossible to do with react-view. There is an open issue to fix this.
 - Any prop that takes an object is broken due to problems in react-view. There is an open issue to fix this.


Some props have not been tested.
I have not done anything realistic with any of the HoistInput callbacks (i.e. onChange, onCommit), just ‘alert’ and ‘console.log’ and the like.
- ButtonGroupInput
   - 	style
- DateInput
    - 	dayPickerProps
    - 	rightElement
    - 	timePickerProps
- JsonInput
    - 	editorProps
- Select
    - 	createMessageFn
    - 	labelField
    - 	loadingMessageFn
    - 	noOptionsMessageFn
    - 	optionRenderer
    - 	queryBuffer
    - 	queryFn
    - 	rsOptions
    - 	valueField
- Slider
    - 	labelRenderer
- TextArea
    - 	onKeyDown

**Comment by peterjcoffman** [comment]
The bug in react-view blocking progress in this issue has been fixed.

https://github.com/uber/react-view/issues/8

Once they do a new release, I can probably finish this issue in short order.

**Comment by peterjcoffman** [comment]
Getting this to build requires adding 
```
        node: {
            fs: 'empty'
        }
```
to configureWebpack.js from hoist-dev-utils.

Not sure why. I followed the instructions here: https://github.com/webpack-contrib/css-loader/issues/447

**Comment by peterjcoffman** [comment]
PR is open here:
https://github.com/xh/toolbox/pull/343
