### ISSUE TITLE
Portfolio - hidden price chart does not load

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#323]
Load up the portfolio example, wait for "Trading Volume" chart to load.  Switch to "Price Chart" tab - note chart is missing.

I've been meaning to revisit how these charts load their data for a while now as it is sub-optimal - currently they both fire off data loads, even though only one can be seen at a time.  Improving that story - perhaps with a better use of the tab container and model loadSupport - might fix this issue - but we should ensure we understand what is going on regardless.

**Comment by peterjcoffman** [comment]
This was a new bug from https://github.com/xh/hoist-react/pull/1505.

The issue is that I was trying to react to an observableRef, but an observableRef is not observable. Only its `current` property is observable. A render should be triggered when the chart is first displayed, but this did not happen since I was not observing the ref properly.

Here is a fix:

https://github.com/xh/hoist-react/pull/1545
