### ISSUE TITLE
Tree w/CheckBox grid example triggers Store.modifyRecords() warning

### ISSUE THREAD

**Issue by amcclain** [xh/toolbox#336]
Checking / unchecking any node in the grid prints the following on the console:

`Store.modifyRecords() called with multiple updates for the same Records. Only the first modification for each Record was processed.`

There is also quite a noticeable flash for the entire dataset that seems to indicate more re-rendering is happening than we would expect or like...

**Comment by amcclain** [comment]
@haynesjm42 thought you might want to look at this re. recent data package updates.

**Comment by haynesjm42** [comment]
Ah yes that example is what prompted that check and warning in Store, but I forgot to actually fix the application code :)

Regarding the flashing - looks like it is only happening in the current snapshot, looks fine on toolbox.xh.io running on v29, so likely related to the ag-Grid upgrade to 22.1? @peterjcoffman

**Comment by peterjcoffman** [comment]
@haynesjm42 Sure looks like it. I tried the current develop build and the same build with ag-grid 21.2. The 

```
Store.modifyRecords() called with multiple updates for the same Records. Only the first modification for each Record was processed.
```
 warning was in both, but the flashing was only visible with ag-grid 22.1.

**Comment by lbwexler** [comment]
@peterjcoffman, @amcclain , @haynesjm42 -- High priority to understand what is going on here with respect to ag-Grid 22.1 and the flashing.  Need to do so before release of our 28.1 and make sure we aren't harming our agGrid performance generally.

**Comment by peterjcoffman** [comment]
@lbwexler 

I believe this is a regression in ag-Grid. I found an ag-Grid issue relating to a similar problem:

https://github.com/ag-grid/ag-grid/issues/3458

Note that 'reactNext' is now the default in ag-Grid 22.1, so the cause is most likely the same.

That issue refers to an internal ag-Grid issue, `AG-3595 React - Data Change Can Result In Flicker`. This appears to be incorrect-- the correct internal issue is `AG-3410 React - Data Change Can Result In Flicker`, which is listed in the [pipeline](https://www.ag-grid.com/ag-grid-pipeline/).

**Comment by lbwexler** [comment]
Yikes this is potentially a show-stopper on this upgrade.  If you read the ticket carefully, it sounds like this relates to rendering internal react components.

While it is not recommended for performance reasons, we do have usages clients that are using custom renderers that render react components.

Can you try to reproduce in grid test and we can triage this?  

We will also want to raise in our enterprise support channel.

**Comment by peterjcoffman** [comment]
I have done a little more investigation.

The flickering issue seems to happen only when we use an `elementRenderer` for a column. I see no flickering on `renderer` columns, and I can reliably introduce flickering by changing a renderer to an elementRenderer.

Furthermore, the problem seems to be aggravated by the fact that our checkbox column in the grid on Toolbox also has `rendererIsComplex: true`. If we don't have `rendererIsComplex: true`, then ag-Grid's [change detection](https://www.ag-grid.com/javascript-grid-change-detection/) will only refresh cells that have changed data. This means that an `elementRenderer` cell will still flicker, but only when the data in that cell has changed. But with `rendererIsComplex`, we force the column to refresh whenever data _anywhere in the grid_ is changed. This is much more distracting, both because the flickering will occur more often and because it will occur when no data has changed.

This means that the example on Toolbox is the worst case. If we don't use `elementRenderer`, there is no flickering at all. If we don't use `rendererIsComplex`, cells will refresh only when changed. It is when we use the two together that we get this distracting flickering.

**Comment by peterjcoffman** [comment]
The cause of the `modifyRecords` warning is that the `SampleTreeGridModel` tries to update a record and all descendants of that record. It gets the list of records to update as follows:

```
            updates = [
                {id: rec.id, isChecked},
                ...rec.allDescendants.map(({id}) => ({id, isChecked}))
            ];
```

However, our `allDescendants` getter method returns a list of all descendants _and the parent record_. So record1.allDescendants.includes(record1) === true. Therefore, the `SampleTreeGridModel` tries to modify the parent twice: once intentionally, then again accidentally because it is in `allDescendants`.

There are two possible fixes:

1. Just update the records in `allDescendants`, not explicity updating the parent record.
2. Change `allDescendants` to exclude the parent record.

**Comment by lbwexler** [comment]
Thanks for jumping on this Peter

Can we just remove the dup's before calling load in whatever way is expedient and clean?  Use a lodash method, or a Map()?

Will help to see a PR -- we don't feel strongly about this -- just especially want to get it cleaned up so it does not distract us from other issues on this grid.

**Comment by haynesjm42** [comment]
Good catch re: the `modifyRecords` call - looks like that call wasn't updated when that api changed during development.

Re: the flickering - I would be suspicious of the changes that ag-Grid made around React components. Didn't they mention adding support for functional components as well? My guess would be that this is a regression on their end - refreshing a cell using a react component should not be causing a flashing where the component is not rendered at all in the cell

**Comment by peterjcoffman** [comment]
PR: https://github.com/xh/toolbox/pull/342

**Comment by lbwexler** [comment]
Thanks for the quick fix here
